name: CD - Publish & Installer

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.0.x"

    - name: Install Windows Desktop workload
      run: dotnet workload install microsoft-net-sdk-windowsdesktop

    - name: Publish WPF
      working-directory: SmartRestaurantSystem
      run: dotnet publish RestaurantWPF/RestaurantWPF.csproj `
              -c Release `
              -o ../publish `
              -r win-x64 `
              --self-contained true `
              /p:PublishSingleFile=true

    - name: Build Setup.exe with Inno Setup
      uses: Minionguyjpro/InnoSetup-Action@v1.0.3
      with:
        path: SmartRestaurantSystem/Installer/installer.iss

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: SmartRestaurant-Setup
        path: SmartRestaurantSystem/Installer/Output/*.exe

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: SmartRestaurantSystem/Installer/Output/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
